### ISSUE TITLE
Unicode SQL Files cause errors

### ISSUE THREAD

**Issue by rohbotics** [robconery/massive-js#130] opened 2015-10-11 23:35 UTC
When  .sql file starts with the unicode byte order mark (`EF BB BF` in hex), massive throws an error when that function is called, ```{ [Error: syntax error at or near "﻿SELECT"] message: 'syntax error at or near "﻿SELECT"' }```

The byte order mark is made of non-ascii characters, and is used to signify the beginning of a Unicode-encoded file.

**Comment by robconery** [comment] 2015-10-12 16:02
That error is from the database, not Massive. My guess is there's a config issue with UTF8 and Postgres here, somehow. What's the query that you're running?

Massive's job is to read the file, pull the contents then hand off to Postgres awaiting the return. In this case an error was returned.

**Comment by rohbotics** [comment] 2015-10-12 16:44
This is my query `SELECT p.* FROM users_projects up, projects p WHERE user_id = $1 and p.project_id = up.project_id;`

The query runs fine when copy-pasted into psql. It also works when cat and piped into psql.

However, certain editors put a [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark) at the beginning of a UTF-8 encoded file. The Byte Order Mark is not shown by text editors, and is generally ignored by most file i/o tools. Massive sends the entire file including the Byte Order Mark to postgres, causing postgres to return an error.

**Comment by robconery** [comment] 2015-10-12 16:58
OK so the issue isn't that the file *name* starts with a BOM, it's that the file *contents* start with a BOM... I think I understand now.

The fix for this would be to run a replace when the contents are scraped (at the start) - if you want to PR please do :).

**Closed** 2015-10-12 23:41 UTC
